default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

production:
  <<: *default
  host: terraform-20210420035451256800000001.cbch251i7aoz.ap-northeast-1.rds.amazonaws.com
  database: production
  # database: app_production
  url: <%= ENV['RR_DATABASE_URL'] %>
  password: ENV['DATABASE_PASSWORD']