default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

production:
  <<: *default
  database: production
  host: <%= ENV['RR_HOST'] %>
  # database: app_production
  # url: <%= ENV['RR_DATABASE_URL'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>

  