default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
  # ↓↓CiecleCI を通すときにコメントアウト
  # password: <%= ENV['MYSQL_ROOT_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development
  
test:
  <<: *default
  database: app_test
  # ↓↓CiecleCI を通すときにコメントイン
  host: 127.0.0.1

production:
  <<: *default
  # url: <%= ENV['DATABASE_URL'] %>
  host: terraform-20210530054545746800000001.cbch251i7aoz.ap-northeast-1.rds.amazonaws.com
  database: production
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  