default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
 # bin/rails db:seed RAILS_ENV=development でパスワードが必要.
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development
  
test:
  <<: *default
  database: app_test
  # ↓↓CircleCI で 127.0.0.1 を使用。ローカル（development）で localhost を使用。
  host: 127.0.0.1
  # ↓↓development 環境であってもなくてもログイン可
  # password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  # host: terraform-20210427110221563100000006.cbch251i7aoz.ap-northeast-1.rds.amazonaws.com
  database: production
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  # database: app_production
  # url: <%= ENV['RR_DATABASE_URL'] %>
  # password: <%= ENV['DATABASE_PASSWORD'] %>

  