version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout
      - run: 
          command: gem install bundler:2.2.11
          working_directory: backend
      - run:
          name: Which bundler?
          command: bundle -v
          working_directory: backend
      - run: 
      - restore_cache:
          keys:
              - v1-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
              - v1-gem-cache-{{ arch }}-{{ .Branch }}-
              - v1-gem-cache-{{ arch }}-
          
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: backend

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - backend/vendor/bundle
