version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers-legacy
        environment:
          RAILS_ENV: test
          DATABASE_HOST: '127.0.0.1'
      - image: circleci/mysql:5.7.30
#    image: circleci/classic:edge

    steps:
      - checkout
      - run:
          name: Install bundler
          command: gem install bundler -v 2.2.15
          working_directory: backend
      - run:
          name: Which bundler?
          command: bundle -v
          working_directory: backend
      - restore_cache:
          keys:
            - gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-{{ arch }}-{{ .Branch }}
            - gem-cache
      - run:  
          name: Bundle Install  
          command:  bundle config set path 'backend/vendor/bundle' 
#          command:  bundle install --jobs=4 --retry=3
          working_directory: backend
      - save_cache:
          key: gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

