version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@1.2.0
  aws-cli: circleci/aws-cli@0.1.16
jobs:
  # buildするjob
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          command: docker-compose build
      - run: sleep 10
      # Tests in backend
      - run:
          name: docker-compose run backend rails db:create RAILS_ENV=test
          command: docker-compose run backend rails db:create RAILS_ENV=test
      - run:
          name: docker-compose run backend rails db:migrate RAILS_ENV=test
          command: docker-compose run backend rails db:migrate RAILS_ENV=test
      - run:
          name: docker-compose run backend bundle exec rspec spec
          command: docker-compose run backend bundle exec rspec spec
      - run:
          name: docker-compose run frontend yarn install
          command: docker-compose run frontend yarn install
      # Tests in Frontend
      - run:
          name: docker-compose run frontend yarn run test
          command: docker-compose run frontend yarn test
       - run:
          name: docker-compose down
          command: docker-compose down

