version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge

    steps:
      - checkout
      - restore_cache:
          keys:
              - v1-gem-cache-{{ arch }}-{{ .Branch/backend }}-{{ checksum "Gemfile.lock" }}
              - v1-gem-cache-{{ arch }}-{{ .Branch/backend }}-
              - v1-gem-cache-{{ arch }}-
          
      - run:
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
          working_directory: backend

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - backend/vendor/bundle
